### ISSUE TITLE
Reading incorrect on 6800h

### ISSUE THREAD

**Issue by BoukeHaarsma23** [BoukeHaarsma23/zenergy#2]
> They seem okay initially albeit high (between 20 and 45 Watts) until I run a game, or start a benchmark... Then it easily goes to 70-ish watts and up and up...
> 
> @BoukeHaarsma23 for example, running DRI_PRIME=1 MANGOHUD=1 vkcube is not too bad: ![Screenshot_20230907_160210](https://user-images.githubusercontent.com/65850835/266451193-980767cd-2891-4aad-a12b-2ee916db2a57.png)
> 
> @BoukeHaarsma23 Whereas running Unigine Heaven benchmark or any newer game results in (159W): ![Screenshot_20230907_160717](https://user-images.githubusercontent.com/65850835/266451960-54e4f11e-4efd-4e5e-8304-d0196a224688.png)

**Comment by BoukeHaarsma23** [comment]
It could be that a scaling factor is off for this CPU. But I'll have to look into it.

**Comment by linuxazo** [comment]
> It could be that a scaling factor is off for this CPU. But I'll have to look into it.

Whenever you get to it, I am willing to help further tests.  
Thank You so much for your efforts @BoukeHaarsma23

**Comment by linuxazo** [comment]
@BoukeHaarsma23 hi again! 
After some more testing... I think I realized what this problem is. 
The CPU power is actually the total CPU and GPU power in my laptop.
So, the fix would be to substract the GPU power from the current value of CPU power to get the real CPU power.  6800H has a TDP of 45W and all my test do point to this solution.
(In my case it's a all AMD laptop with 6800H CPU and 6700M dedicated GPU.

**Comment by linuxazo** [comment]
@BoukeHaarsma23 
Dear Developer, 
after further testing, I can assure you that this bug is not necessarily a bug, it is just the way AMD is computing their power draws.
Same reporting can be seen in MSI Afterburner on Windows.
It is showing total CPU and GPU power usage instead of GPU power usage.

Many thanks :)

**Comment by linuxazo** [comment]
@BoukeHaarsma23 Thank You for closing this bug report. 
Just to add that, afaik, this discrepancy specifically seems to affect dual AMD GPU combinations...
iGPU+dGPU (e.g. AMD Advantage laptops)
